---
- name: tweak grub settings
  lineinfile:
    dest: /etc/default/grub
    regexp: GRUB_CMDLINE_LINUX=.*
    line: GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"
  register: grubbed
  sudo: yes

- name: apply changed grub settings
  command: update-grub
  sudo: yes

- include: docker.yml

- name: pull docker images
  docker: image={{ item }} state=present
  with_items:
  - jupyter/nature-demo
  - jupyter/configurable-http-proxy
  - jupyter/tmpnb
  sudo: yes

- name: reboot
  command: shutdown -r now "Ansible updated grub"
  async: 0
  poll: 0
  sudo: yes
  ignore_errors: true
  when: grubbed | changed

- name: wait for server to relaunch
  local_action: wait_for host={{ inventory_hostname }} state=started
