---
- name: tweak grub settings
  lineinfile:
    dest: /etc/default/grub
    regexp: GRUB_CMDLINE_LINUX=.*
    line: GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"
  register: grubbed
  sudo: yes

- name: apply changed grub settings
  command: update-grub
  sudo: yes
  when: grubbed | changed

- include: docker.yml

- name: pull docker images
  command: docker pull {{ item }}
  with_items:
  - jupyter/nature-demo
  - jupyter/configurable-http-proxy
  - jupyter/tmpnb
  sudo: yes

- name: reboot
  command: shutdown -r now "Ansible updated grub"
  async: 0
  poll: 0
  sudo: yes
  ignore_errors: true
  when: grubbed | changed

- name: wait for server to relaunch
  local_action: wait_for host={{ inventory_hostname }} state=started
  when: grubbed | changed

- name: iptables configuration
  command: iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to 8000
  sudo: yes

- name: configproxy
  docker:
    state: running
    image: jupyter/configurable-http-proxy
    detach: true
    net: host
    name: configproxy
    env:
      CONFIGPROXY_AUTH_TOKEN: "{{ configproxy_auth_token }}"
    command: --default-target http://127.0.0.1:9999

- name: tmpnb
  docker:
    state: running
    image: jupyter/tmpnb
    detach: true
    net: host
    name: tmpnb
    env:
      CONFIGPROXY_AUTH_TOKEN: "{{ configproxy_auth_token }}"
    volumes: /var/run/docker.sock:/docker.sock
    command: >
      python orchestrate.py
      --pool_size={{ tmpnb_pool_size }}
      --cull_timeout={{ tmpnb_cull_timeout }}
      --cull_period={{ tmpnb_cull_period }}
      --image={{ tmpnb_image }}
      --docker_version={{ tmpnb_docker_version }}
      --static_files={{ tmpnb_static_files }}
      --redirect_uri={{ tmpnb_redirect_uri }}
      --command='{{ tmpnb_command }}'
      --max_dock_workers={{ tmpnb_max_dock_workers }}
      --mem-limit={{ tmpnb_mem_limit }}
      --cpu-shares={{ tmpnb_cpu_shares }}
