---
- hosts: notebook
  vars_files:
  - ['secrets.yml', 'secrets.vault.yml']
  - vars.yml
  roles:
  - common
  - notebook

- hosts: proxy
  vars_files:
  - ['secrets.yml', 'secrets.vault.yml']
  - vars.yml
  roles:
  - common
  - proxy
