---
- name: pull docker image for user containers
  command: docker pull {{ tmpnb_image }}
  sudo: yes

- name: configuration directories
  file: state=directory dest={{ item }} mode=0755
  with_items:
  - "{{ nginx_config_dir }}"
  sudo: yes

- name: SSL credentials
  template: src={{ item.from }} dest={{ item.to }} mode=0644
  with_items:
  - from: tmpnb.org.key.j2
    to: "{{ ssl_key_path }}"
  - from: tmpnb.org.crt.j2
    to: "{{ ssl_cert_path }}"
  sudo: yes
  notify:
  - reload nginx configuration

- name: nginx configuration
  template: src=nginx.conf.j2 dest={{ nginx_config_dir }}/nginx.conf mode=0644
  sudo: yes
  notify:
  - reload nginx configuration

- name: copy the Dockerfile to the nginx configuration directory
  template: src=Dockerfile_nginx.j2 dest={{ nginx_config_dir }}/Dockerfile mode=0644
  sudo: yes

- name: build tmpnb nginx image
  docker_image:
    path: "{{ nginx_config_dir }}"
    name: tmpnb_nginx
    state: build
  sudo: yes
 
- name: launch nginx
  docker:
    image: tmpnb_nginx
    state: running
    name: nginx
    volumes: "{{ nginx_volumes }}"
    ports: "{{ nginx_ports }}"
    restart_policy: always
